### ISSUE TITLE
When executing integration test on linux box, we get: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not a subtype

### ISSUE THREAD

**Issue by bhecquet** [bhecquet/seleniumRobot#113]
Scenario to reproduce:
Start integration test on linux box (here ubuntu 16.04 with openjdk 8)

Expected result:
tests should be run correctly

Current result:
We get: 

`javax.xml.parsers.FactoryConfigurationError: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:311)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
	at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:120)
	at com.seleniumtests.util.PackageUtility.getVersionFromPom(PackageUtility.java:42)
	at com.seleniumtests.util.PackageUtility.getVersionFromPom(PackageUtility.java:87)
	at com.seleniumtests.util.PackageUtility.getVersion(PackageUtility.java:128)
	at com.seleniumtests.driver.DriverExtractor.extractDriver(DriverExtractor.java:91)
	at com.seleniumtests.browserfactory.IDesktopCapabilityFactory.prepareBinaryAndDriver(IDesktopCapabilityFactory.java:41)
	at com.seleniumtests.browserfactory.IDesktopCapabilityFactory.createCapabilities(IDesktopCapabilityFactory.java:67)
	at com.seleniumtests.browserfactory.AbstractWebDriverFactory.<init>(AbstractWebDriverFactory.java:43)
	at com.seleniumtests.browserfactory.ChromeDriverFactory.<init>(ChromeDriverFactory.java:28)
	at com.seleniumtests.driver.WebUIDriver.createRemoteWebDriver(WebUIDriver.java:95)
	at com.seleniumtests.driver.WebUIDriver.createWebDriver(WebUIDriver.java:289)
	at com.seleniumtests.driver.WebUIDriver.getWebDriver(WebUIDriver.java:201)
	at com.seleniumtests.driver.WebUIDriver.getWebDriver(WebUIDriver.java:185)
	at com.seleniumtests.uipage.BasePage.init(BasePage.java:51)
	at com.seleniumtests.uipage.BasePage.<init>(BasePage.java:47)
	at com.seleniumtests.uipage.PageObject.<init>(PageObject.java:110)
	at com.seleniumtests.it.driver.support.pages.DriverTestPage.<init>(DriverTestPage.java:131)
	at com.seleniumtests.it.driver.support.pages.DriverTestPage.<init>(DriverTestPage.java:127)
	at com.seleniumtests.it.driver.TestUiSelect.initDriver(TestUiSelect.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.RuntimeException: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:308)
	... 46 more
Caused by: java.util.ServiceConfigurationError: javax.xml.parsers.DocumentBuilderFactory: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
	... 46 more
`

**Comment by bhecquet** [comment]
See last comment of https://github.com/jenkinsci/gitlab-plugin/issues/430
