### ISSUE TITLE
Cannot create driver in @BeforeMethod because proxy param is not initialized

### ISSUE THREAD

**Issue by bhecquet** [bhecquet/seleniumRobot#137]
Scenario to reproduce:
execute test testContextDriverBlockingBeforeMethod by disabling blocking on @BeforeMethod (line 468 for now: `if (configMethod.isBeforeMethodConfiguration() || configMethod.isAfterMethodConfiguration()) {`

Expected result:
no blocking, driver is created

Current result:
NullPointerException
`
class java.lang.NullPointerException: null
at org.openqa.selenium.htmlunit.HtmlUnitDriver.setProxySettings(HtmlUnitDriver.java:511)
at org.openqa.selenium.htmlunit.HtmlUnitDriver.<init>(HtmlUnitDriver.java:281)
at com.seleniumtests.browserfactory.HtmlUnitDriverFactory.createNativeDriver(HtmlUnitDriverFactory.java:32)
at com.seleniumtests.browserfactory.AbstractWebDriverFactory.createWebDriver(AbstractWebDriverFactory.java:73)
at com.seleniumtests.driver.WebUIDriver.createRemoteWebDriver(WebUIDriver.java:125)
`

Other context information
In @BeforeMethod, thread context has not been updated, so proxy type is still `null` which is refused by driver

**Comment by bhecquet** [comment]
Creating driver in @BeforeClass is also refused due to TestType not being initialized
