### ISSUE TITLE
Stackoverflow error

### ISSUE THREAD

**Issue by bhecquet** [bhecquet/seleniumRobot#211]
When driver is blocked error is raised (ok with that)
But when we try to get a snapshot, we may have;

class java.lang.StackOverflowError: null
at java.net.URI$Parser.parseIPv4Address(URI.java:3332)
at java.net.URI$Parser.parseServer(URI.java:3234)
at java.net.URI$Parser.parseAuthority(URI.java:3155)
at java.net.URI$Parser.parseHierarchical(URI.java:3097)
at java.net.URI$Parser.parse(URI.java:3053)
at java.net.URI.<init>(URI.java:588)
at okhttp3.HttpUrl.uri(HttpUrl.java:379)
at okhttp3.internal.connection.RouteSelector.resetNextProxy(RouteSelector.java:129)
at okhttp3.internal.connection.RouteSelector.<init>(RouteSelector.java:63)
at okhttp3.internal.connection.StreamAllocation.<init>(StreamAllocation.java:101)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:112)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall.execute(RealCall.java:77)
at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandles(RemoteWebDriver.java:456)
at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:105)
at com.sun.proxy.$Proxy8.getWindowHandles(Unknown Source)
at org.openqa.selenium.support.events.EventFiringWebDriver.getWindowHandles(EventFiringWebDriver.java:216)
at com.seleniumtests.driver.CustomEventFiringWebDriver.getWindowHandles(CustomEventFiringWebDriver.java:211)
at com.seleniumtests.driver.screenshots.ScreenshotUtil.captureWebPages(ScreenshotUtil.java:277)
at com.seleniumtests.driver.screenshots.ScreenshotUtil.capture(ScreenshotUtil.java:145)
at com.seleniumtests.driver.screenshots.ScreenshotUtil.capture(ScreenshotUtil.java:111)
at com.seleniumtests.driver.screenshots.ScreenshotUtil.capture(ScreenshotUtil.java:99)
at com.seleniumtests.driver.DriverExceptionListener.onException(DriverExceptionListener.java:189)
at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$0(EventFiringWebDriver.java:84)
at com.sun.proxy.$Proxy7.onException(Unknown Source)
at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:107)
at com.sun.proxy.$Proxy8.getWindowHandles(Unknown Source)
at org.openqa.selenium.support.events.EventFiringWebDriver.getWindowHandles(EventFiringWebDriver.java:216)
at com.seleniumtests.driver.CustomEventFiringWebDriver.getWindowHandles(CustomEventFiringWebDriver.java:211)
at com.seleniumtests.driver.screenshots.ScreenshotUtil.captureWebPages(ScreenshotUtil.java:277)
at com.seleniumtests.driver.screenshots.ScreenshotUtil.capture(ScreenshotUtil.java:145)
at com.seleniumtests.driver.screenshots.ScreenshotUtil.capture(ScreenshotUtil.java:111)
at com.seleniumtests.driver.screenshots.ScreenshotUtil.capture(ScreenshotUtil.java:99)
at com.seleniumtests.driver.DriverExceptionListener.onException(DriverExceptionListener.java:189)
at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$0(EventFiringWebDriver.java:84)
at com.sun.proxy.$Proxy7.onException(Unknown Source)
at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:107)
at com.sun.proxy.$Proxy8.getWindowHandles(Unknown Source)

**Comment by bhecquet** [comment]
ScreenshotUtil calls the driver whereas it's not able to reply. We should check in exception listener, if the stacktrace already contains a reference to exception listener
