### ISSUE TITLE
NPE when generating report and screenshot HTML is not there

### ISSUE THREAD

**Issue by bhecquet** [bhecquet/seleniumRobot#422]
with 4.18.0

```
: Error generating temp report
java.lang.NullPointerException
                at com.seleniumtests.reporter.logger.TestStep.moveAttachments(TestStep.java:331)
                at com.seleniumtests.reporter.reporters.ReporterControler.cleanAttachments(ReporterControler.java:368)
                at com.seleniumtests.reporter.reporters.ReporterControler.generateReport(ReporterControler.java:95)
                at com.seleniumtests.core.runner.SeleniumRobotTestListener.generateTempReport(SeleniumRobotTestListener.java:187)
                at com.seleniumtests.core.runner.SeleniumRobotTestListener.onTestFullyFinished(SeleniumRobotTestListener.java:116)
                at com.seleniumtests.core.runner.SeleniumRobotTestPlan.finishTestMethod_aroundBody2(SeleniumRobotTestPlan.java:108)
                at com.seleniumtests.core.runner.SeleniumRobotTestPlan$AjcClosure3.run(SeleniumRobotTestPlan.java:1)

```

**Comment by bhecquet** [comment]
Due to option "captureSnapshot=false"
